<?php
/**
 * JobsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Email Validation API — Enterprise-grade Email Verification
 *
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailSafePro\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use MailSafePro\ApiException;
use MailSafePro\Configuration;
use MailSafePro\FormDataProcessor;
use MailSafePro\HeaderSelector;
use MailSafePro\ObjectSerializer;

/**
 * JobsApi Class Doc Comment
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class JobsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createJobJobsV1JobsPost' => [
            'application/json',
        ],
        'createJobJobsV1JobsPost_0' => [
            'application/json',
        ],
        'getJobResultsJobsV1JobsJobIdResultsGet' => [
            'application/json',
        ],
        'getJobResultsJobsV1JobsJobIdResultsGet_0' => [
            'application/json',
        ],
        'getJobStatusJobsV1JobsJobIdGet' => [
            'application/json',
        ],
        'getJobStatusJobsV1JobsJobIdGet_0' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createJobJobsV1JobsPost
     *
     * Create validation job
     *
     * @param  \MailSafePro\Model\JobCreateRequest $job_create_request job_create_request (required)
     * @param  string|null $x_idempotency_key x_idempotency_key (optional)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createJobJobsV1JobsPost'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MailSafePro\Model\JobCreateResponse|\MailSafePro\Model\HTTPValidationError
     */
    public function createJobJobsV1JobsPost($job_create_request, $x_idempotency_key = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createJobJobsV1JobsPost'][0])
    {
        list($response) = $this->createJobJobsV1JobsPostWithHttpInfo($job_create_request, $x_idempotency_key, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation createJobJobsV1JobsPostWithHttpInfo
     *
     * Create validation job
     *
     * @param  \MailSafePro\Model\JobCreateRequest $job_create_request (required)
     * @param  string|null $x_idempotency_key (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createJobJobsV1JobsPost'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MailSafePro\Model\JobCreateResponse|\MailSafePro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createJobJobsV1JobsPostWithHttpInfo($job_create_request, $x_idempotency_key = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createJobJobsV1JobsPost'][0])
    {
        $request = $this->createJobJobsV1JobsPostRequest($job_create_request, $x_idempotency_key, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\JobCreateResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MailSafePro\Model\JobCreateResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\JobCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createJobJobsV1JobsPostAsync
     *
     * Create validation job
     *
     * @param  \MailSafePro\Model\JobCreateRequest $job_create_request (required)
     * @param  string|null $x_idempotency_key (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createJobJobsV1JobsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createJobJobsV1JobsPostAsync($job_create_request, $x_idempotency_key = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createJobJobsV1JobsPost'][0])
    {
        return $this->createJobJobsV1JobsPostAsyncWithHttpInfo($job_create_request, $x_idempotency_key, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createJobJobsV1JobsPostAsyncWithHttpInfo
     *
     * Create validation job
     *
     * @param  \MailSafePro\Model\JobCreateRequest $job_create_request (required)
     * @param  string|null $x_idempotency_key (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createJobJobsV1JobsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createJobJobsV1JobsPostAsyncWithHttpInfo($job_create_request, $x_idempotency_key = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createJobJobsV1JobsPost'][0])
    {
        $returnType = '\MailSafePro\Model\JobCreateResponse';
        $request = $this->createJobJobsV1JobsPostRequest($job_create_request, $x_idempotency_key, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createJobJobsV1JobsPost'
     *
     * @param  \MailSafePro\Model\JobCreateRequest $job_create_request (required)
     * @param  string|null $x_idempotency_key (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createJobJobsV1JobsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createJobJobsV1JobsPostRequest($job_create_request, $x_idempotency_key = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createJobJobsV1JobsPost'][0])
    {

        // verify the required parameter 'job_create_request' is set
        if ($job_create_request === null || (is_array($job_create_request) && count($job_create_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $job_create_request when calling createJobJobsV1JobsPost'
            );
        }





        $resourcePath = '/jobs/v1/jobs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_idempotency_key !== null) {
            $headerParams['X-Idempotency-Key'] = ObjectSerializer::toHeaderValue($x_idempotency_key);
        }
        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($job_create_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($job_create_request));
            } else {
                $httpBody = $job_create_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createJobJobsV1JobsPost_0
     *
     * Create validation job
     *
     * @param  \MailSafePro\Model\JobCreateRequest $job_create_request job_create_request (required)
     * @param  string|null $x_idempotency_key x_idempotency_key (optional)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createJobJobsV1JobsPost_0'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MailSafePro\Model\JobCreateResponse|\MailSafePro\Model\HTTPValidationError
     */
    public function createJobJobsV1JobsPost_0($job_create_request, $x_idempotency_key = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createJobJobsV1JobsPost_0'][0])
    {
        list($response) = $this->createJobJobsV1JobsPost_0WithHttpInfo($job_create_request, $x_idempotency_key, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation createJobJobsV1JobsPost_0WithHttpInfo
     *
     * Create validation job
     *
     * @param  \MailSafePro\Model\JobCreateRequest $job_create_request (required)
     * @param  string|null $x_idempotency_key (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createJobJobsV1JobsPost_0'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MailSafePro\Model\JobCreateResponse|\MailSafePro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createJobJobsV1JobsPost_0WithHttpInfo($job_create_request, $x_idempotency_key = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createJobJobsV1JobsPost_0'][0])
    {
        $request = $this->createJobJobsV1JobsPost_0Request($job_create_request, $x_idempotency_key, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\JobCreateResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MailSafePro\Model\JobCreateResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\JobCreateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createJobJobsV1JobsPost_0Async
     *
     * Create validation job
     *
     * @param  \MailSafePro\Model\JobCreateRequest $job_create_request (required)
     * @param  string|null $x_idempotency_key (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createJobJobsV1JobsPost_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createJobJobsV1JobsPost_0Async($job_create_request, $x_idempotency_key = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createJobJobsV1JobsPost_0'][0])
    {
        return $this->createJobJobsV1JobsPost_0AsyncWithHttpInfo($job_create_request, $x_idempotency_key, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createJobJobsV1JobsPost_0AsyncWithHttpInfo
     *
     * Create validation job
     *
     * @param  \MailSafePro\Model\JobCreateRequest $job_create_request (required)
     * @param  string|null $x_idempotency_key (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createJobJobsV1JobsPost_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createJobJobsV1JobsPost_0AsyncWithHttpInfo($job_create_request, $x_idempotency_key = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createJobJobsV1JobsPost_0'][0])
    {
        $returnType = '\MailSafePro\Model\JobCreateResponse';
        $request = $this->createJobJobsV1JobsPost_0Request($job_create_request, $x_idempotency_key, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createJobJobsV1JobsPost_0'
     *
     * @param  \MailSafePro\Model\JobCreateRequest $job_create_request (required)
     * @param  string|null $x_idempotency_key (optional)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createJobJobsV1JobsPost_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createJobJobsV1JobsPost_0Request($job_create_request, $x_idempotency_key = null, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['createJobJobsV1JobsPost_0'][0])
    {

        // verify the required parameter 'job_create_request' is set
        if ($job_create_request === null || (is_array($job_create_request) && count($job_create_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $job_create_request when calling createJobJobsV1JobsPost_0'
            );
        }





        $resourcePath = '/jobs/v1/jobs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_idempotency_key !== null) {
            $headerParams['X-Idempotency-Key'] = ObjectSerializer::toHeaderValue($x_idempotency_key);
        }
        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($job_create_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($job_create_request));
            } else {
                $httpBody = $job_create_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getJobResultsJobsV1JobsJobIdResultsGet
     *
     * Get job results (paged)
     *
     * @param  string $job_id job_id (required)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $size size (optional, default to 500)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MailSafePro\Model\JobResultsPage|\MailSafePro\Model\HTTPValidationError
     */
    public function getJobResultsJobsV1JobsJobIdResultsGet($job_id, $page = 1, $size = 500, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet'][0])
    {
        list($response) = $this->getJobResultsJobsV1JobsJobIdResultsGetWithHttpInfo($job_id, $page, $size, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation getJobResultsJobsV1JobsJobIdResultsGetWithHttpInfo
     *
     * Get job results (paged)
     *
     * @param  string $job_id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $size (optional, default to 500)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MailSafePro\Model\JobResultsPage|\MailSafePro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getJobResultsJobsV1JobsJobIdResultsGetWithHttpInfo($job_id, $page = 1, $size = 500, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet'][0])
    {
        $request = $this->getJobResultsJobsV1JobsJobIdResultsGetRequest($job_id, $page, $size, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\JobResultsPage',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MailSafePro\Model\JobResultsPage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\JobResultsPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getJobResultsJobsV1JobsJobIdResultsGetAsync
     *
     * Get job results (paged)
     *
     * @param  string $job_id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $size (optional, default to 500)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getJobResultsJobsV1JobsJobIdResultsGetAsync($job_id, $page = 1, $size = 500, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet'][0])
    {
        return $this->getJobResultsJobsV1JobsJobIdResultsGetAsyncWithHttpInfo($job_id, $page, $size, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getJobResultsJobsV1JobsJobIdResultsGetAsyncWithHttpInfo
     *
     * Get job results (paged)
     *
     * @param  string $job_id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $size (optional, default to 500)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getJobResultsJobsV1JobsJobIdResultsGetAsyncWithHttpInfo($job_id, $page = 1, $size = 500, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet'][0])
    {
        $returnType = '\MailSafePro\Model\JobResultsPage';
        $request = $this->getJobResultsJobsV1JobsJobIdResultsGetRequest($job_id, $page, $size, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getJobResultsJobsV1JobsJobIdResultsGet'
     *
     * @param  string $job_id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $size (optional, default to 500)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getJobResultsJobsV1JobsJobIdResultsGetRequest($job_id, $page = 1, $size = 500, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet'][0])
    {

        // verify the required parameter 'job_id' is set
        if ($job_id === null || (is_array($job_id) && count($job_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $job_id when calling getJobResultsJobsV1JobsJobIdResultsGet'
            );
        }






        $resourcePath = '/jobs/v1/jobs/{job_id}/results';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($job_id !== null) {
            $resourcePath = str_replace(
                '{' . 'job_id' . '}',
                ObjectSerializer::toPathValue($job_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getJobResultsJobsV1JobsJobIdResultsGet_0
     *
     * Get job results (paged)
     *
     * @param  string $job_id job_id (required)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $size size (optional, default to 500)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet_0'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MailSafePro\Model\JobResultsPage|\MailSafePro\Model\HTTPValidationError
     */
    public function getJobResultsJobsV1JobsJobIdResultsGet_0($job_id, $page = 1, $size = 500, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet_0'][0])
    {
        list($response) = $this->getJobResultsJobsV1JobsJobIdResultsGet_0WithHttpInfo($job_id, $page, $size, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation getJobResultsJobsV1JobsJobIdResultsGet_0WithHttpInfo
     *
     * Get job results (paged)
     *
     * @param  string $job_id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $size (optional, default to 500)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet_0'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MailSafePro\Model\JobResultsPage|\MailSafePro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getJobResultsJobsV1JobsJobIdResultsGet_0WithHttpInfo($job_id, $page = 1, $size = 500, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet_0'][0])
    {
        $request = $this->getJobResultsJobsV1JobsJobIdResultsGet_0Request($job_id, $page, $size, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\JobResultsPage',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MailSafePro\Model\JobResultsPage',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\JobResultsPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getJobResultsJobsV1JobsJobIdResultsGet_0Async
     *
     * Get job results (paged)
     *
     * @param  string $job_id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $size (optional, default to 500)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getJobResultsJobsV1JobsJobIdResultsGet_0Async($job_id, $page = 1, $size = 500, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet_0'][0])
    {
        return $this->getJobResultsJobsV1JobsJobIdResultsGet_0AsyncWithHttpInfo($job_id, $page, $size, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getJobResultsJobsV1JobsJobIdResultsGet_0AsyncWithHttpInfo
     *
     * Get job results (paged)
     *
     * @param  string $job_id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $size (optional, default to 500)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getJobResultsJobsV1JobsJobIdResultsGet_0AsyncWithHttpInfo($job_id, $page = 1, $size = 500, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet_0'][0])
    {
        $returnType = '\MailSafePro\Model\JobResultsPage';
        $request = $this->getJobResultsJobsV1JobsJobIdResultsGet_0Request($job_id, $page, $size, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getJobResultsJobsV1JobsJobIdResultsGet_0'
     *
     * @param  string $job_id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $size (optional, default to 500)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getJobResultsJobsV1JobsJobIdResultsGet_0Request($job_id, $page = 1, $size = 500, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobResultsJobsV1JobsJobIdResultsGet_0'][0])
    {

        // verify the required parameter 'job_id' is set
        if ($job_id === null || (is_array($job_id) && count($job_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $job_id when calling getJobResultsJobsV1JobsJobIdResultsGet_0'
            );
        }






        $resourcePath = '/jobs/v1/jobs/{job_id}/results';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $size,
            'size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($job_id !== null) {
            $resourcePath = str_replace(
                '{' . 'job_id' . '}',
                ObjectSerializer::toPathValue($job_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getJobStatusJobsV1JobsJobIdGet
     *
     * Get job status
     *
     * @param  string $job_id job_id (required)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobStatusJobsV1JobsJobIdGet'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MailSafePro\Model\JobStatusResponse|\MailSafePro\Model\HTTPValidationError
     */
    public function getJobStatusJobsV1JobsJobIdGet($job_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobStatusJobsV1JobsJobIdGet'][0])
    {
        list($response) = $this->getJobStatusJobsV1JobsJobIdGetWithHttpInfo($job_id, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation getJobStatusJobsV1JobsJobIdGetWithHttpInfo
     *
     * Get job status
     *
     * @param  string $job_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobStatusJobsV1JobsJobIdGet'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MailSafePro\Model\JobStatusResponse|\MailSafePro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getJobStatusJobsV1JobsJobIdGetWithHttpInfo($job_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobStatusJobsV1JobsJobIdGet'][0])
    {
        $request = $this->getJobStatusJobsV1JobsJobIdGetRequest($job_id, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\JobStatusResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MailSafePro\Model\JobStatusResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\JobStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getJobStatusJobsV1JobsJobIdGetAsync
     *
     * Get job status
     *
     * @param  string $job_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobStatusJobsV1JobsJobIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getJobStatusJobsV1JobsJobIdGetAsync($job_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobStatusJobsV1JobsJobIdGet'][0])
    {
        return $this->getJobStatusJobsV1JobsJobIdGetAsyncWithHttpInfo($job_id, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getJobStatusJobsV1JobsJobIdGetAsyncWithHttpInfo
     *
     * Get job status
     *
     * @param  string $job_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobStatusJobsV1JobsJobIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getJobStatusJobsV1JobsJobIdGetAsyncWithHttpInfo($job_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobStatusJobsV1JobsJobIdGet'][0])
    {
        $returnType = '\MailSafePro\Model\JobStatusResponse';
        $request = $this->getJobStatusJobsV1JobsJobIdGetRequest($job_id, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getJobStatusJobsV1JobsJobIdGet'
     *
     * @param  string $job_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobStatusJobsV1JobsJobIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getJobStatusJobsV1JobsJobIdGetRequest($job_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobStatusJobsV1JobsJobIdGet'][0])
    {

        // verify the required parameter 'job_id' is set
        if ($job_id === null || (is_array($job_id) && count($job_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $job_id when calling getJobStatusJobsV1JobsJobIdGet'
            );
        }




        $resourcePath = '/jobs/v1/jobs/{job_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($job_id !== null) {
            $resourcePath = str_replace(
                '{' . 'job_id' . '}',
                ObjectSerializer::toPathValue($job_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getJobStatusJobsV1JobsJobIdGet_0
     *
     * Get job status
     *
     * @param  string $job_id job_id (required)
     * @param  string|null $x_api_key x_api_key (optional)
     * @param  string|null $authorization authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobStatusJobsV1JobsJobIdGet_0'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MailSafePro\Model\JobStatusResponse|\MailSafePro\Model\HTTPValidationError
     */
    public function getJobStatusJobsV1JobsJobIdGet_0($job_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobStatusJobsV1JobsJobIdGet_0'][0])
    {
        list($response) = $this->getJobStatusJobsV1JobsJobIdGet_0WithHttpInfo($job_id, $x_api_key, $authorization, $contentType);
        return $response;
    }

    /**
     * Operation getJobStatusJobsV1JobsJobIdGet_0WithHttpInfo
     *
     * Get job status
     *
     * @param  string $job_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobStatusJobsV1JobsJobIdGet_0'] to see the possible values for this operation
     *
     * @throws \MailSafePro\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MailSafePro\Model\JobStatusResponse|\MailSafePro\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getJobStatusJobsV1JobsJobIdGet_0WithHttpInfo($job_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobStatusJobsV1JobsJobIdGet_0'][0])
    {
        $request = $this->getJobStatusJobsV1JobsJobIdGet_0Request($job_id, $x_api_key, $authorization, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\JobStatusResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\MailSafePro\Model\HTTPValidationError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MailSafePro\Model\JobStatusResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\JobStatusResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MailSafePro\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getJobStatusJobsV1JobsJobIdGet_0Async
     *
     * Get job status
     *
     * @param  string $job_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobStatusJobsV1JobsJobIdGet_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getJobStatusJobsV1JobsJobIdGet_0Async($job_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobStatusJobsV1JobsJobIdGet_0'][0])
    {
        return $this->getJobStatusJobsV1JobsJobIdGet_0AsyncWithHttpInfo($job_id, $x_api_key, $authorization, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getJobStatusJobsV1JobsJobIdGet_0AsyncWithHttpInfo
     *
     * Get job status
     *
     * @param  string $job_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobStatusJobsV1JobsJobIdGet_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getJobStatusJobsV1JobsJobIdGet_0AsyncWithHttpInfo($job_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobStatusJobsV1JobsJobIdGet_0'][0])
    {
        $returnType = '\MailSafePro\Model\JobStatusResponse';
        $request = $this->getJobStatusJobsV1JobsJobIdGet_0Request($job_id, $x_api_key, $authorization, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getJobStatusJobsV1JobsJobIdGet_0'
     *
     * @param  string $job_id (required)
     * @param  string|null $x_api_key (optional)
     * @param  string|null $authorization (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getJobStatusJobsV1JobsJobIdGet_0'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getJobStatusJobsV1JobsJobIdGet_0Request($job_id, $x_api_key = null, $authorization = null, string $contentType = self::contentTypes['getJobStatusJobsV1JobsJobIdGet_0'][0])
    {

        // verify the required parameter 'job_id' is set
        if ($job_id === null || (is_array($job_id) && count($job_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $job_id when calling getJobStatusJobsV1JobsJobIdGet_0'
            );
        }




        $resourcePath = '/jobs/v1/jobs/{job_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_api_key !== null) {
            $headerParams['X-API-Key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }
        // header params
        if ($authorization !== null) {
            $headerParams['authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($job_id !== null) {
            $resourcePath = str_replace(
                '{' . 'job_id' . '}',
                ObjectSerializer::toPathValue($job_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
