<?php
/**
 * BatchEmailResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Email Validation API — Enterprise-grade Email Verification
 *
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailSafePro\Model;

use \ArrayAccess;
use \MailSafePro\ObjectSerializer;

/**
 * BatchEmailResponse Class Doc Comment
 *
 * @category Class
 * @description Batch validation response
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BatchEmailResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BatchEmailResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'count' => 'int',
        'valid_count' => 'int',
        'invalid_count' => 'int',
        'processing_time' => 'float',
        'average_time' => 'float',
        'results' => '\MailSafePro\Model\EmailResponse[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'count' => null,
        'valid_count' => null,
        'invalid_count' => null,
        'processing_time' => null,
        'average_time' => null,
        'results' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'count' => false,
        'valid_count' => false,
        'invalid_count' => false,
        'processing_time' => false,
        'average_time' => false,
        'results' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'count' => 'count',
        'valid_count' => 'valid_count',
        'invalid_count' => 'invalid_count',
        'processing_time' => 'processing_time',
        'average_time' => 'average_time',
        'results' => 'results'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'count' => 'setCount',
        'valid_count' => 'setValidCount',
        'invalid_count' => 'setInvalidCount',
        'processing_time' => 'setProcessingTime',
        'average_time' => 'setAverageTime',
        'results' => 'setResults'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'count' => 'getCount',
        'valid_count' => 'getValidCount',
        'invalid_count' => 'getInvalidCount',
        'processing_time' => 'getProcessingTime',
        'average_time' => 'getAverageTime',
        'results' => 'getResults'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('count', $data ?? [], null);
        $this->setIfExists('valid_count', $data ?? [], null);
        $this->setIfExists('invalid_count', $data ?? [], null);
        $this->setIfExists('processing_time', $data ?? [], null);
        $this->setIfExists('average_time', $data ?? [], null);
        $this->setIfExists('results', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['count'] === null) {
            $invalidProperties[] = "'count' can't be null";
        }
        if (($this->container['count'] < 0)) {
            $invalidProperties[] = "invalid value for 'count', must be bigger than or equal to 0.";
        }

        if ($this->container['valid_count'] === null) {
            $invalidProperties[] = "'valid_count' can't be null";
        }
        if (($this->container['valid_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'valid_count', must be bigger than or equal to 0.";
        }

        if ($this->container['invalid_count'] === null) {
            $invalidProperties[] = "'invalid_count' can't be null";
        }
        if (($this->container['invalid_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'invalid_count', must be bigger than or equal to 0.";
        }

        if ($this->container['processing_time'] === null) {
            $invalidProperties[] = "'processing_time' can't be null";
        }
        if (($this->container['processing_time'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'processing_time', must be bigger than or equal to 0.0.";
        }

        if ($this->container['average_time'] === null) {
            $invalidProperties[] = "'average_time' can't be null";
        }
        if (($this->container['average_time'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'average_time', must be bigger than or equal to 0.0.";
        }

        if ($this->container['results'] === null) {
            $invalidProperties[] = "'results' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets count
     *
     * @return int
     */
    public function getCount()
    {
        return $this->container['count'];
    }

    /**
     * Sets count
     *
     * @param int $count Total emails processed
     *
     * @return self
     */
    public function setCount($count)
    {
        if (is_null($count)) {
            throw new \InvalidArgumentException('non-nullable count cannot be null');
        }

        if (($count < 0)) {
            throw new \InvalidArgumentException('invalid value for $count when calling BatchEmailResponse., must be bigger than or equal to 0.');
        }

        $this->container['count'] = $count;

        return $this;
    }

    /**
     * Gets valid_count
     *
     * @return int
     */
    public function getValidCount()
    {
        return $this->container['valid_count'];
    }

    /**
     * Sets valid_count
     *
     * @param int $valid_count Number of valid emails
     *
     * @return self
     */
    public function setValidCount($valid_count)
    {
        if (is_null($valid_count)) {
            throw new \InvalidArgumentException('non-nullable valid_count cannot be null');
        }

        if (($valid_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $valid_count when calling BatchEmailResponse., must be bigger than or equal to 0.');
        }

        $this->container['valid_count'] = $valid_count;

        return $this;
    }

    /**
     * Gets invalid_count
     *
     * @return int
     */
    public function getInvalidCount()
    {
        return $this->container['invalid_count'];
    }

    /**
     * Sets invalid_count
     *
     * @param int $invalid_count Number of invalid emails
     *
     * @return self
     */
    public function setInvalidCount($invalid_count)
    {
        if (is_null($invalid_count)) {
            throw new \InvalidArgumentException('non-nullable invalid_count cannot be null');
        }

        if (($invalid_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $invalid_count when calling BatchEmailResponse., must be bigger than or equal to 0.');
        }

        $this->container['invalid_count'] = $invalid_count;

        return $this;
    }

    /**
     * Gets processing_time
     *
     * @return float
     */
    public function getProcessingTime()
    {
        return $this->container['processing_time'];
    }

    /**
     * Sets processing_time
     *
     * @param float $processing_time Total processing time in seconds
     *
     * @return self
     */
    public function setProcessingTime($processing_time)
    {
        if (is_null($processing_time)) {
            throw new \InvalidArgumentException('non-nullable processing_time cannot be null');
        }

        if (($processing_time < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $processing_time when calling BatchEmailResponse., must be bigger than or equal to 0.0.');
        }

        $this->container['processing_time'] = $processing_time;

        return $this;
    }

    /**
     * Gets average_time
     *
     * @return float
     */
    public function getAverageTime()
    {
        return $this->container['average_time'];
    }

    /**
     * Sets average_time
     *
     * @param float $average_time Average processing time per email
     *
     * @return self
     */
    public function setAverageTime($average_time)
    {
        if (is_null($average_time)) {
            throw new \InvalidArgumentException('non-nullable average_time cannot be null');
        }

        if (($average_time < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $average_time when calling BatchEmailResponse., must be bigger than or equal to 0.0.');
        }

        $this->container['average_time'] = $average_time;

        return $this;
    }

    /**
     * Gets results
     *
     * @return \MailSafePro\Model\EmailResponse[]
     */
    public function getResults()
    {
        return $this->container['results'];
    }

    /**
     * Sets results
     *
     * @param \MailSafePro\Model\EmailResponse[] $results Individual validation results
     *
     * @return self
     */
    public function setResults($results)
    {
        if (is_null($results)) {
            throw new \InvalidArgumentException('non-nullable results cannot be null');
        }
        $this->container['results'] = $results;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


