<?php
/**
 * EmailResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Email Validation API — Enterprise-grade Email Verification
 *
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailSafePro\Model;

use \ArrayAccess;
use \MailSafePro\ObjectSerializer;

/**
 * EmailResponse Class Doc Comment
 *
 * @category Class
 * @description Comprehensive email validation response
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EmailResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EmailResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'email' => 'string',
        'valid' => 'bool',
        'detail' => 'string',
        'processing_time' => 'float',
        'provider' => 'string',
        'reputation' => 'float',
        'fingerprint' => 'string',
        'quality_score' => 'float',
        'risk_level' => '\MailSafePro\Model\RiskLevelEnum',
        'suggestions' => 'string[]',
        'smtp' => '\MailSafePro\Model\SMTPInfo',
        'dns' => '\MailSafePro\Model\DNSInfo',
        'risk_score' => 'float',
        'validation_tier' => 'string',
        'suggested_action' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'email' => null,
        'valid' => null,
        'detail' => null,
        'processing_time' => null,
        'provider' => null,
        'reputation' => null,
        'fingerprint' => null,
        'quality_score' => null,
        'risk_level' => null,
        'suggestions' => null,
        'smtp' => null,
        'dns' => null,
        'risk_score' => null,
        'validation_tier' => null,
        'suggested_action' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'email' => false,
        'valid' => false,
        'detail' => false,
        'processing_time' => true,
        'provider' => true,
        'reputation' => true,
        'fingerprint' => true,
        'quality_score' => true,
        'risk_level' => true,
        'suggestions' => false,
        'smtp' => true,
        'dns' => true,
        'risk_score' => true,
        'validation_tier' => true,
        'suggested_action' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'email' => 'email',
        'valid' => 'valid',
        'detail' => 'detail',
        'processing_time' => 'processing_time',
        'provider' => 'provider',
        'reputation' => 'reputation',
        'fingerprint' => 'fingerprint',
        'quality_score' => 'quality_score',
        'risk_level' => 'risk_level',
        'suggestions' => 'suggestions',
        'smtp' => 'smtp',
        'dns' => 'dns',
        'risk_score' => 'risk_score',
        'validation_tier' => 'validation_tier',
        'suggested_action' => 'suggested_action'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'email' => 'setEmail',
        'valid' => 'setValid',
        'detail' => 'setDetail',
        'processing_time' => 'setProcessingTime',
        'provider' => 'setProvider',
        'reputation' => 'setReputation',
        'fingerprint' => 'setFingerprint',
        'quality_score' => 'setQualityScore',
        'risk_level' => 'setRiskLevel',
        'suggestions' => 'setSuggestions',
        'smtp' => 'setSmtp',
        'dns' => 'setDns',
        'risk_score' => 'setRiskScore',
        'validation_tier' => 'setValidationTier',
        'suggested_action' => 'setSuggestedAction'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'email' => 'getEmail',
        'valid' => 'getValid',
        'detail' => 'getDetail',
        'processing_time' => 'getProcessingTime',
        'provider' => 'getProvider',
        'reputation' => 'getReputation',
        'fingerprint' => 'getFingerprint',
        'quality_score' => 'getQualityScore',
        'risk_level' => 'getRiskLevel',
        'suggestions' => 'getSuggestions',
        'smtp' => 'getSmtp',
        'dns' => 'getDns',
        'risk_score' => 'getRiskScore',
        'validation_tier' => 'getValidationTier',
        'suggested_action' => 'getSuggestedAction'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('valid', $data ?? [], null);
        $this->setIfExists('detail', $data ?? [], '');
        $this->setIfExists('processing_time', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('reputation', $data ?? [], null);
        $this->setIfExists('fingerprint', $data ?? [], null);
        $this->setIfExists('quality_score', $data ?? [], null);
        $this->setIfExists('risk_level', $data ?? [], null);
        $this->setIfExists('suggestions', $data ?? [], null);
        $this->setIfExists('smtp', $data ?? [], null);
        $this->setIfExists('dns', $data ?? [], null);
        $this->setIfExists('risk_score', $data ?? [], null);
        $this->setIfExists('validation_tier', $data ?? [], null);
        $this->setIfExists('suggested_action', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ((mb_strlen($this->container['email']) > 254)) {
            $invalidProperties[] = "invalid value for 'email', the character length must be smaller than or equal to 254.";
        }

        if ((mb_strlen($this->container['email']) < 5)) {
            $invalidProperties[] = "invalid value for 'email', the character length must be bigger than or equal to 5.";
        }

        if ($this->container['valid'] === null) {
            $invalidProperties[] = "'valid' can't be null";
        }
        if (!is_null($this->container['processing_time']) && ($this->container['processing_time'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'processing_time', must be bigger than or equal to 0.0.";
        }

        if (!is_null($this->container['reputation']) && ($this->container['reputation'] > 1.0)) {
            $invalidProperties[] = "invalid value for 'reputation', must be smaller than or equal to 1.0.";
        }

        if (!is_null($this->container['reputation']) && ($this->container['reputation'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'reputation', must be bigger than or equal to 0.0.";
        }

        if (!is_null($this->container['quality_score']) && ($this->container['quality_score'] > 1.0)) {
            $invalidProperties[] = "invalid value for 'quality_score', must be smaller than or equal to 1.0.";
        }

        if (!is_null($this->container['quality_score']) && ($this->container['quality_score'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'quality_score', must be bigger than or equal to 0.0.";
        }

        if (!is_null($this->container['risk_score']) && ($this->container['risk_score'] > 1.0)) {
            $invalidProperties[] = "invalid value for 'risk_score', must be smaller than or equal to 1.0.";
        }

        if (!is_null($this->container['risk_score']) && ($this->container['risk_score'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'risk_score', must be bigger than or equal to 0.0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email Validated email address
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        if ((mb_strlen($email) > 254)) {
            throw new \InvalidArgumentException('invalid length for $email when calling EmailResponse., must be smaller than or equal to 254.');
        }
        if ((mb_strlen($email) < 5)) {
            throw new \InvalidArgumentException('invalid length for $email when calling EmailResponse., must be bigger than or equal to 5.');
        }

        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets valid
     *
     * @return bool
     */
    public function getValid()
    {
        return $this->container['valid'];
    }

    /**
     * Sets valid
     *
     * @param bool $valid Overall validation result
     *
     * @return self
     */
    public function setValid($valid)
    {
        if (is_null($valid)) {
            throw new \InvalidArgumentException('non-nullable valid cannot be null');
        }
        $this->container['valid'] = $valid;

        return $this;
    }

    /**
     * Gets detail
     *
     * @return string|null
     */
    public function getDetail()
    {
        return $this->container['detail'];
    }

    /**
     * Sets detail
     *
     * @param string|null $detail Validation details summary
     *
     * @return self
     */
    public function setDetail($detail)
    {
        if (is_null($detail)) {
            throw new \InvalidArgumentException('non-nullable detail cannot be null');
        }
        $this->container['detail'] = $detail;

        return $this;
    }

    /**
     * Gets processing_time
     *
     * @return float|null
     */
    public function getProcessingTime()
    {
        return $this->container['processing_time'];
    }

    /**
     * Sets processing_time
     *
     * @param float|null $processing_time processing_time
     *
     * @return self
     */
    public function setProcessingTime($processing_time)
    {
        if (is_null($processing_time)) {
            array_push($this->openAPINullablesSetToNull, 'processing_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('processing_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($processing_time) && ($processing_time < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $processing_time when calling EmailResponse., must be bigger than or equal to 0.0.');
        }

        $this->container['processing_time'] = $processing_time;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return string|null
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param string|null $provider provider
     *
     * @return self
     */
    public function setProvider($provider)
    {
        if (is_null($provider)) {
            array_push($this->openAPINullablesSetToNull, 'provider');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('provider', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets reputation
     *
     * @return float|null
     */
    public function getReputation()
    {
        return $this->container['reputation'];
    }

    /**
     * Sets reputation
     *
     * @param float|null $reputation reputation
     *
     * @return self
     */
    public function setReputation($reputation)
    {
        if (is_null($reputation)) {
            array_push($this->openAPINullablesSetToNull, 'reputation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reputation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($reputation) && ($reputation > 1.0)) {
            throw new \InvalidArgumentException('invalid value for $reputation when calling EmailResponse., must be smaller than or equal to 1.0.');
        }
        if (!is_null($reputation) && ($reputation < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $reputation when calling EmailResponse., must be bigger than or equal to 0.0.');
        }

        $this->container['reputation'] = $reputation;

        return $this;
    }

    /**
     * Gets fingerprint
     *
     * @return string|null
     */
    public function getFingerprint()
    {
        return $this->container['fingerprint'];
    }

    /**
     * Sets fingerprint
     *
     * @param string|null $fingerprint fingerprint
     *
     * @return self
     */
    public function setFingerprint($fingerprint)
    {
        if (is_null($fingerprint)) {
            array_push($this->openAPINullablesSetToNull, 'fingerprint');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fingerprint', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fingerprint'] = $fingerprint;

        return $this;
    }

    /**
     * Gets quality_score
     *
     * @return float|null
     */
    public function getQualityScore()
    {
        return $this->container['quality_score'];
    }

    /**
     * Sets quality_score
     *
     * @param float|null $quality_score quality_score
     *
     * @return self
     */
    public function setQualityScore($quality_score)
    {
        if (is_null($quality_score)) {
            array_push($this->openAPINullablesSetToNull, 'quality_score');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('quality_score', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($quality_score) && ($quality_score > 1.0)) {
            throw new \InvalidArgumentException('invalid value for $quality_score when calling EmailResponse., must be smaller than or equal to 1.0.');
        }
        if (!is_null($quality_score) && ($quality_score < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $quality_score when calling EmailResponse., must be bigger than or equal to 0.0.');
        }

        $this->container['quality_score'] = $quality_score;

        return $this;
    }

    /**
     * Gets risk_level
     *
     * @return \MailSafePro\Model\RiskLevelEnum|null
     */
    public function getRiskLevel()
    {
        return $this->container['risk_level'];
    }

    /**
     * Sets risk_level
     *
     * @param \MailSafePro\Model\RiskLevelEnum|null $risk_level risk_level
     *
     * @return self
     */
    public function setRiskLevel($risk_level)
    {
        if (is_null($risk_level)) {
            array_push($this->openAPINullablesSetToNull, 'risk_level');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('risk_level', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['risk_level'] = $risk_level;

        return $this;
    }

    /**
     * Gets suggestions
     *
     * @return string[]|null
     */
    public function getSuggestions()
    {
        return $this->container['suggestions'];
    }

    /**
     * Sets suggestions
     *
     * @param string[]|null $suggestions Improvement suggestions
     *
     * @return self
     */
    public function setSuggestions($suggestions)
    {
        if (is_null($suggestions)) {
            throw new \InvalidArgumentException('non-nullable suggestions cannot be null');
        }
        $this->container['suggestions'] = $suggestions;

        return $this;
    }

    /**
     * Gets smtp
     *
     * @return \MailSafePro\Model\SMTPInfo|null
     */
    public function getSmtp()
    {
        return $this->container['smtp'];
    }

    /**
     * Sets smtp
     *
     * @param \MailSafePro\Model\SMTPInfo|null $smtp smtp
     *
     * @return self
     */
    public function setSmtp($smtp)
    {
        if (is_null($smtp)) {
            array_push($this->openAPINullablesSetToNull, 'smtp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('smtp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['smtp'] = $smtp;

        return $this;
    }

    /**
     * Gets dns
     *
     * @return \MailSafePro\Model\DNSInfo|null
     */
    public function getDns()
    {
        return $this->container['dns'];
    }

    /**
     * Sets dns
     *
     * @param \MailSafePro\Model\DNSInfo|null $dns dns
     *
     * @return self
     */
    public function setDns($dns)
    {
        if (is_null($dns)) {
            array_push($this->openAPINullablesSetToNull, 'dns');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dns', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dns'] = $dns;

        return $this;
    }

    /**
     * Gets risk_score
     *
     * @return float|null
     */
    public function getRiskScore()
    {
        return $this->container['risk_score'];
    }

    /**
     * Sets risk_score
     *
     * @param float|null $risk_score risk_score
     *
     * @return self
     */
    public function setRiskScore($risk_score)
    {
        if (is_null($risk_score)) {
            array_push($this->openAPINullablesSetToNull, 'risk_score');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('risk_score', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($risk_score) && ($risk_score > 1.0)) {
            throw new \InvalidArgumentException('invalid value for $risk_score when calling EmailResponse., must be smaller than or equal to 1.0.');
        }
        if (!is_null($risk_score) && ($risk_score < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $risk_score when calling EmailResponse., must be bigger than or equal to 0.0.');
        }

        $this->container['risk_score'] = $risk_score;

        return $this;
    }

    /**
     * Gets validation_tier
     *
     * @return string|null
     */
    public function getValidationTier()
    {
        return $this->container['validation_tier'];
    }

    /**
     * Sets validation_tier
     *
     * @param string|null $validation_tier validation_tier
     *
     * @return self
     */
    public function setValidationTier($validation_tier)
    {
        if (is_null($validation_tier)) {
            array_push($this->openAPINullablesSetToNull, 'validation_tier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('validation_tier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['validation_tier'] = $validation_tier;

        return $this;
    }

    /**
     * Gets suggested_action
     *
     * @return string|null
     */
    public function getSuggestedAction()
    {
        return $this->container['suggested_action'];
    }

    /**
     * Sets suggested_action
     *
     * @param string|null $suggested_action suggested_action
     *
     * @return self
     */
    public function setSuggestedAction($suggested_action)
    {
        if (is_null($suggested_action)) {
            array_push($this->openAPINullablesSetToNull, 'suggested_action');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('suggested_action', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['suggested_action'] = $suggested_action;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


