<?php
/**
 * KeyRotationRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Email Validation API — Enterprise-grade Email Verification
 *
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailSafePro\Model;

use \ArrayAccess;
use \MailSafePro\ObjectSerializer;

/**
 * KeyRotationRequest Class Doc Comment
 *
 * @category Class
 * @description API Key rotation request
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class KeyRotationRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'KeyRotationRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'old_key' => 'string',
        'new_key' => 'string',
        'grace_period' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'old_key' => null,
        'new_key' => null,
        'grace_period' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'old_key' => false,
        'new_key' => false,
        'grace_period' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'old_key' => 'old_key',
        'new_key' => 'new_key',
        'grace_period' => 'grace_period'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'old_key' => 'setOldKey',
        'new_key' => 'setNewKey',
        'grace_period' => 'setGracePeriod'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'old_key' => 'getOldKey',
        'new_key' => 'getNewKey',
        'grace_period' => 'getGracePeriod'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('old_key', $data ?? [], null);
        $this->setIfExists('new_key', $data ?? [], null);
        $this->setIfExists('grace_period', $data ?? [], 86400);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['old_key'] === null) {
            $invalidProperties[] = "'old_key' can't be null";
        }
        if ((mb_strlen($this->container['old_key']) > 128)) {
            $invalidProperties[] = "invalid value for 'old_key', the character length must be smaller than or equal to 128.";
        }

        if ((mb_strlen($this->container['old_key']) < 32)) {
            $invalidProperties[] = "invalid value for 'old_key', the character length must be bigger than or equal to 32.";
        }

        if ($this->container['new_key'] === null) {
            $invalidProperties[] = "'new_key' can't be null";
        }
        if ((mb_strlen($this->container['new_key']) > 128)) {
            $invalidProperties[] = "invalid value for 'new_key', the character length must be smaller than or equal to 128.";
        }

        if ((mb_strlen($this->container['new_key']) < 32)) {
            $invalidProperties[] = "invalid value for 'new_key', the character length must be bigger than or equal to 32.";
        }

        if (!is_null($this->container['grace_period']) && ($this->container['grace_period'] > 2592000)) {
            $invalidProperties[] = "invalid value for 'grace_period', must be smaller than or equal to 2592000.";
        }

        if (!is_null($this->container['grace_period']) && ($this->container['grace_period'] < 0)) {
            $invalidProperties[] = "invalid value for 'grace_period', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets old_key
     *
     * @return string
     */
    public function getOldKey()
    {
        return $this->container['old_key'];
    }

    /**
     * Sets old_key
     *
     * @param string $old_key Current API key to rotate from
     *
     * @return self
     */
    public function setOldKey($old_key)
    {
        if (is_null($old_key)) {
            throw new \InvalidArgumentException('non-nullable old_key cannot be null');
        }
        if ((mb_strlen($old_key) > 128)) {
            throw new \InvalidArgumentException('invalid length for $old_key when calling KeyRotationRequest., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($old_key) < 32)) {
            throw new \InvalidArgumentException('invalid length for $old_key when calling KeyRotationRequest., must be bigger than or equal to 32.');
        }

        $this->container['old_key'] = $old_key;

        return $this;
    }

    /**
     * Gets new_key
     *
     * @return string
     */
    public function getNewKey()
    {
        return $this->container['new_key'];
    }

    /**
     * Sets new_key
     *
     * @param string $new_key New API key to rotate to
     *
     * @return self
     */
    public function setNewKey($new_key)
    {
        if (is_null($new_key)) {
            throw new \InvalidArgumentException('non-nullable new_key cannot be null');
        }
        if ((mb_strlen($new_key) > 128)) {
            throw new \InvalidArgumentException('invalid length for $new_key when calling KeyRotationRequest., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($new_key) < 32)) {
            throw new \InvalidArgumentException('invalid length for $new_key when calling KeyRotationRequest., must be bigger than or equal to 32.');
        }

        $this->container['new_key'] = $new_key;

        return $this;
    }

    /**
     * Gets grace_period
     *
     * @return int|null
     */
    public function getGracePeriod()
    {
        return $this->container['grace_period'];
    }

    /**
     * Sets grace_period
     *
     * @param int|null $grace_period Grace period in seconds (max 30 days)
     *
     * @return self
     */
    public function setGracePeriod($grace_period)
    {
        if (is_null($grace_period)) {
            throw new \InvalidArgumentException('non-nullable grace_period cannot be null');
        }

        if (($grace_period > 2592000)) {
            throw new \InvalidArgumentException('invalid value for $grace_period when calling KeyRotationRequest., must be smaller than or equal to 2592000.');
        }
        if (($grace_period < 0)) {
            throw new \InvalidArgumentException('invalid value for $grace_period when calling KeyRotationRequest., must be bigger than or equal to 0.');
        }

        $this->container['grace_period'] = $grace_period;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


