<?php
/**
 * PlanEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Email Validation API — Enterprise-grade Email Verification
 *
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailSafePro\Model;
use \MailSafePro\ObjectSerializer;

/**
 * PlanEnum Class Doc Comment
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PlanEnum
{
    /**
     * Possible values of this enum
     */
    public const FREE = 'FREE';

    public const PREMIUM = 'PREMIUM';

    public const ENTERPRISE = 'ENTERPRISE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FREE,
            self::PREMIUM,
            self::ENTERPRISE
        ];
    }
}


