<?php
/**
 * APIKeysApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Email Validation API — Enterprise-grade Email Verification
 *
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MailSafePro\Test\Api;

use \MailSafePro\Configuration;
use \MailSafePro\ApiException;
use \MailSafePro\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * APIKeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class APIKeysApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createApiKeyApiKeysPost
     *
     * Create Api Key.
     *
     */
    public function testCreateApiKeyApiKeysPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createApiKeyApiKeysPost_0
     *
     * Create Api Key.
     *
     */
    public function testCreateApiKeyApiKeysPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for forceSyncApiKeysForceSyncPost
     *
     * Force Sync.
     *
     */
    public function testForceSyncApiKeysForceSyncPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for forceSyncApiKeysForceSyncPost_0
     *
     * Force Sync.
     *
     */
    public function testForceSyncApiKeysForceSyncPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiKeyValueApiKeysKeyHashValueGet
     *
     * Get Api Key Value.
     *
     */
    public function testGetApiKeyValueApiKeysKeyHashValueGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiKeyValueApiKeysKeyHashValueGet_0
     *
     * Get Api Key Value.
     *
     */
    public function testGetApiKeyValueApiKeysKeyHashValueGet0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUsageApiKeysUsageGet
     *
     * Get Usage.
     *
     */
    public function testGetUsageApiKeysUsageGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUsageApiKeysUsageGet_0
     *
     * Get Usage.
     *
     */
    public function testGetUsageApiKeysUsageGet0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listApiKeysApiKeysGet
     *
     * List Api Keys.
     *
     */
    public function testListApiKeysApiKeysGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listApiKeysApiKeysGet_0
     *
     * List Api Keys.
     *
     */
    public function testListApiKeysApiKeysGet0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for repairUserDataEndpointApiKeysRepairDataPost
     *
     * Repair User Data Endpoint.
     *
     */
    public function testRepairUserDataEndpointApiKeysRepairDataPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for repairUserDataEndpointApiKeysRepairDataPost_0
     *
     * Repair User Data Endpoint.
     *
     */
    public function testRepairUserDataEndpointApiKeysRepairDataPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeApiKeyApiKeysKeyHashRevokeDelete
     *
     * Revoke Api Key.
     *
     */
    public function testRevokeApiKeyApiKeysKeyHashRevokeDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeApiKeyApiKeysKeyHashRevokeDelete_0
     *
     * Revoke Api Key.
     *
     */
    public function testRevokeApiKeyApiKeysKeyHashRevokeDelete0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rotateApiKeyApiKeysKeyHashRotatePost
     *
     * Rotate Api Key.
     *
     */
    public function testRotateApiKeyApiKeysKeyHashRotatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rotateApiKeyApiKeysKeyHashRotatePost_0
     *
     * Rotate Api Key.
     *
     */
    public function testRotateApiKeyApiKeysKeyHashRotatePost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for syncPlanKeysApiKeysSyncPlanKeysPost
     *
     * Sync Plan Keys.
     *
     */
    public function testSyncPlanKeysApiKeysSyncPlanKeysPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for syncPlanKeysApiKeysSyncPlanKeysPost_0
     *
     * Sync Plan Keys.
     *
     */
    public function testSyncPlanKeysApiKeysSyncPlanKeysPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
