<?php
/**
 * BillingApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Email Validation API — Enterprise-grade Email Verification
 *
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MailSafePro\Test\Api;

use \MailSafePro\Configuration;
use \MailSafePro\ApiException;
use \MailSafePro\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BillingApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BillingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for changePlanBillingBillingChangePlanPost
     *
     * Change Plan.
     *
     */
    public function testChangePlanBillingBillingChangePlanPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for changePlanBillingBillingChangePlanPost_0
     *
     * Change Plan.
     *
     */
    public function testChangePlanBillingBillingChangePlanPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCheckoutSessionBillingBillingCreateCheckoutSessionPost
     *
     * Create Checkout Session.
     *
     */
    public function testCreateCheckoutSessionBillingBillingCreateCheckoutSessionPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCheckoutSessionBillingBillingCreateCheckoutSessionPost_0
     *
     * Create Checkout Session.
     *
     */
    public function testCreateCheckoutSessionBillingBillingCreateCheckoutSessionPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSubscriptionBillingBillingSubscriptionGet
     *
     * Get Subscription.
     *
     */
    public function testGetSubscriptionBillingBillingSubscriptionGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSubscriptionBillingBillingSubscriptionGet_0
     *
     * Get Subscription.
     *
     */
    public function testGetSubscriptionBillingBillingSubscriptionGet0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for stripeWebhookBillingBillingWebhookPost
     *
     * Stripe Webhook.
     *
     */
    public function testStripeWebhookBillingBillingWebhookPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for stripeWebhookBillingBillingWebhookPost_0
     *
     * Stripe Webhook.
     *
     */
    public function testStripeWebhookBillingBillingWebhookPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testNotificationBillingBillingTestNotificationPost
     *
     * Test Notification.
     *
     */
    public function testTestNotificationBillingBillingTestNotificationPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testNotificationBillingBillingTestNotificationPost_0
     *
     * Test Notification.
     *
     */
    public function testTestNotificationBillingBillingTestNotificationPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
