<?php
/**
 * WebhooksApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Email Validation API — Enterprise-grade Email Verification
 *
 * API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com
 *
 * The version of the OpenAPI document: 2.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MailSafePro\Test\Api;

use \MailSafePro\Configuration;
use \MailSafePro\ApiException;
use \MailSafePro\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WebhooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  MailSafePro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhooksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createWebhookWebhooksManagementWebhooksPost
     *
     * Create Webhook.
     *
     */
    public function testCreateWebhookWebhooksManagementWebhooksPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWebhookWebhooksManagementWebhooksWebhookIdDelete
     *
     * Delete Webhook.
     *
     */
    public function testDeleteWebhookWebhooksManagementWebhooksWebhookIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDeliveriesWebhooksManagementWebhooksWebhookIdDeliveriesGet
     *
     * Get Deliveries.
     *
     */
    public function testGetDeliveriesWebhooksManagementWebhooksWebhookIdDeliveriesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWebhookWebhooksManagementWebhooksWebhookIdGet
     *
     * Get Webhook.
     *
     */
    public function testGetWebhookWebhooksManagementWebhooksWebhookIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWebhooksWebhooksManagementWebhooksGet
     *
     * List Webhooks.
     *
     */
    public function testListWebhooksWebhooksManagementWebhooksGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for registerEndpointWebhooksV1WebhooksEndpointsRegisterPost
     *
     * Register Endpoint.
     *
     */
    public function testRegisterEndpointWebhooksV1WebhooksEndpointsRegisterPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for registerEndpointWebhooksV1WebhooksEndpointsRegisterPost_0
     *
     * Register Endpoint.
     *
     */
    public function testRegisterEndpointWebhooksV1WebhooksEndpointsRegisterPost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rotateSecretWebhooksV1WebhooksEndpointsRotatePost
     *
     * Rotate Secret.
     *
     */
    public function testRotateSecretWebhooksV1WebhooksEndpointsRotatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rotateSecretWebhooksV1WebhooksEndpointsRotatePost_0
     *
     * Rotate Secret.
     *
     */
    public function testRotateSecretWebhooksV1WebhooksEndpointsRotatePost0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testWebhookWebhooksManagementWebhooksWebhookIdTestPost
     *
     * Test Webhook.
     *
     */
    public function testTestWebhookWebhooksManagementWebhooksWebhookIdTestPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWebhookWebhooksManagementWebhooksWebhookIdPatch
     *
     * Update Webhook.
     *
     */
    public function testUpdateWebhookWebhooksManagementWebhooksWebhookIdPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
